#include <dgl/inference/envs.h>

namespace dgl {
namespace inference {

const char* DGL_INFER_MASTER_HOST = "DGL_INFER_MASTER_HOST";
const char* DGL_INFER_MASTER_PORT = "DGL_INFER_MASTER_PORT";
const char* DGL_INFER_NODE_RANK = "DGL_INFER_NODE_RANK";
const char* DGL_INFER_LOCAL_RANK = "DGL_INFER_LOCAL_RANK";
const char* DGL_INFER_NUM_NODES = "DGL_INFER_NUM_NODES";
const char* DGL_INFER_NUM_DEVICES_PER_NODE = "DGL_INFER_NUM_DEVICES_PER_NODE";
const char* DGL_INFER_IFACE = "DGL_INFER_IFACE";
const char* DGL_INFER_ACTOR_PROCESS_ROLE = "DGL_INFER_ACTOR_PROCESS_ROLE";
const char* DGL_INFER_ACTOR_PROCESS_GLOBAL_ID = "DGL_INFER_ACTOR_PROCESS_GLOBAL_ID";

}
}
