import os
from enum import Enum

DGL_INFER_MASTER_HOST = "DGL_INFER_MASTER_HOST"
DGL_INFER_MASTER_PORT = "DGL_INFER_MASTER_PORT"
DGL_INFER_NODE_RANK = "DGL_INFER_NODE_RANK"
DGL_INFER_LOCAL_RANK = "DGL_INFER_LOCAL_RANK"
DGL_INFER_NUM_NODES = "DGL_INFER_NUM_NODES"
DGL_INFER_NUM_DEVICES_PER_NODE = "DGL_INFER_NUM_DEVICES_PER_NODE"
DGL_INFER_IFACE = "DGL_INFER_IFACE"
DGL_INFER_ACTOR_PROCESS_ROLE = "DGL_INFER_ACTOR_PROCESS_ROLE"
DGL_INFER_ACTOR_PROCESS_GLOBAL_ID = "DGL_INFER_ACTOR_PROCESS_GLOBAL_ID"
DGL_INFER_IP_CONFIG_PATH = "DGL_INFER_IP_CONFIG_PATH"
DGL_INFER_GRAPH_CONFIG_PATH = "DGL_INFER_GRAPH_CONFIG_PATH"

DGL_INFER_PARALLELIZATION_TYPE = "DGL_INFER_PARALLELIZATION_TYPE"
DGL_INFER_USING_PRECOMPUTED_AGGREGATIONS = "DGL_INFER_USING_PRECOMPUTED_AGGREGATIONS"

class ParallelizationType(Enum):
    DATA = 0
    P3 = 1
    VERTEX_CUT = 2
